//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyaku {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hyaku.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME OVER!.
        /// </summary>
        internal static string GameOverCaption {
            get {
                return ResourceManager.GetString("GameOverCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game over....
        /// </summary>
        internal static string GameOverMessage {
            get {
                return ResourceManager.GetString("GameOverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The availible-space counter went below zero..
        /// </summary>
        internal static string LessThanZeroMessage {
            get {
                return ResourceManager.GetString("LessThanZeroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The availible-space counter went above the maximum..
        /// </summary>
        internal static string MoreThanMaxMessage {
            get {
                return ResourceManager.GetString("MoreThanMaxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohhh! Over the top!.
        /// </summary>
        internal static string PushedPastTopMessage {
            get {
                return ResourceManager.GetString("PushedPastTopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s the end of the game..
        /// </summary>
        internal static string RanOutOfSpaceMessage {
            get {
                return ResourceManager.GetString("RanOutOfSpaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Game?.
        /// </summary>
        internal static string ResetGameCaption {
            get {
                return ResourceManager.GetString("ResetGameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your progress and score will be lost..
        /// </summary>
        internal static string ResetGameQuestion {
            get {
                return ResourceManager.GetString("ResetGameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Game.
        /// </summary>
        internal static string RestoreGameCaption {
            get {
                return ResourceManager.GetString("RestoreGameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to resume your saved game?.
        /// </summary>
        internal static string RestoreGameQuestion {
            get {
                return ResourceManager.GetString("RestoreGameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Game.
        /// </summary>
        internal static string SaveGameCaption {
            get {
                return ResourceManager.GetString("SaveGameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your game?.
        /// </summary>
        internal static string SaveGameQuestion {
            get {
                return ResourceManager.GetString("SaveGameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown issue caused a game-over..
        /// </summary>
        internal static string UnknownGameOverMessage {
            get {
                return ResourceManager.GetString("UnknownGameOverMessage", resourceCulture);
            }
        }
    }
}
